// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kn.web.core.Models;

namespace kn.web.core.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20210525143946_AddUpdateTableUser")]
    partial class AddUpdateTableUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("kn.web.core.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("antena")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("fecha_evento")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("fecha_recepcion")
                        .HasColumnType("datetime");

                    b.Property<float>("ignicion")
                        .HasColumnType("float");

                    b.Property<string>("info_adicional")
                        .HasColumnType("longtext");

                    b.Property<float>("latitud")
                        .HasColumnType("float");

                    b.Property<float>("longitud")
                        .HasColumnType("float");

                    b.Property<string>("plataforma")
                        .HasColumnType("longtext");

                    b.Property<string>("posicion")
                        .HasColumnType("longtext");

                    b.Property<int>("tipo_evento")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Events");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("kn.web.core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CorporateName")
                        .HasColumnType("longtext");

                    b.Property<int>("IsAdmin")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
